### ISSUE TITLE
How to run composer as non-root in docker-compose?

### ISSUE THREAD

**Issue by essana3** [composer/docker#163]
Hello, I am trying to create a Docker Dev Environment.
While doing so, I created the following service in my docker-compose.yaml file.
```
composer:
    build:
      context: .
      dockerfile: docker/composer.dockerfile
    volumes:
      - ./src:/var/www/html
```
composer.dockerfile:
```
FROM composer

WORKDIR /var/www/html

ENTRYPOINT [ "composer", "--ignore-platform-req", "--no-scripts" ]
```
each time I run:
`docker-compose run --rm composer create-project laravel/laravel .`
the files are created by root so I can't modify them on my host machine.

How do I run the composer command as a non-root user using docker-compose?
